# Hi! this is a minimal config file for pond

author_name = 'Sahil Upasane'
blog_name = '404salads Croutons'

# supported accent colors thanks to pico :D
# default amber blue cyan fuchsia green grey indigo jade lime orange pink pumpkin purple red sand slate violet yellow zinc
accent_color =  'lime'
